theme: jekyll-theme-minimal
title: Kaitlin Parente
description: Hello! My name is Kaitlin Parente and I am an aspiring Software Engineer. Most of my work and skills can be found here, but I am constantly adding new work to my site. Check back frequently for new projects and posts!
